spring:
  application:
    name: sales-service
  kafka:
    auto-offset-reset: latest
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: sales-service
  data:
    mongodb:
      uri: ${MONGO_DB_URL}
      database: ${MONGO_DB_NAME}
  aws:
    s3:
      bucket-name: sr-test-sales
      region: us-east-1
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}

server:
  port: 8083